# Generated by Django 5.1.7 on 2025-06-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productcode',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcodeid',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
